"""
============================================================================
 RUN  --  systemic_model
============================================================================
 THE DRIVER. This is what you execute:  python3 run.py

 It runs the whole model end to end, prints every table in readable form,
 runs the sensitivity sweep on the judgment-call scores, and saves a single
 results.json you can feed to a report generator or diff against last month.

 You normally do not edit this file. To change WHAT the model says, edit
 calibration.py. To change HOW the math works, edit engine.py. This file just
 orchestrates and presents.
============================================================================
"""
import json, copy
import numpy as np
import calibration as C
import engine as E


def _clean_json(x):
    """Replace NaN/Inf with None so generated JSON is strict-parser safe."""
    import math as _m
    if isinstance(x, dict):
        return {k: _clean_json(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [_clean_json(v) for v in x]
    if isinstance(x, float) and (_m.isnan(x) or _m.isinf(x)):
        return None
    return x


def _fmt_pct(x, width=4):
    return ("{:>%d.0f}" % width).format(x * 100) if x == x else f"{'n/a':>{width}}"


def print_exposure_tables(results, thr):
    print("\n" + "=" * 74)
    print("TABLE 1 -- Broad exposures: P(max drawdown > X within horizon)")
    print("=" * 74)
    header = f"{'Exposure':18s} {'Hz':4s} " + " ".join(f">{int(t*100):>2d}%" for t in thr)
    print(header)
    for nm, byhz in results.items():
        for hz in C.HORIZON_LABELS:
            row = byhz[hz]["exceedance"]
            print(f"{nm:18s} {hz:4s} " + " ".join(_fmt_pct(v) for v in row))
        print()


def print_recovery_table(results):
    print("=" * 74)
    print("TABLE 2 -- S&P 500 recovery by drawdown bucket (12-month window)")
    print("           the ~30% mandate line is visible where P(recover) collapses")
    print("=" * 74)
    _mm = int(C.MANDATE_MONTHS)
    print(f"{'Drawdown':12s} {'Freq':>6s} {'MedianRec':>10s} {('P(rec<'+str(_mm)+'m)'):>14s}")
    for r in results["S&P 500"]["12m"]["recovery"]:
        lo, hi = r["bucket"]
        med = f"{r['median_months']:.1f}mo" if r["median_months"] == r["median_months"] else "n/a"
        print(f"{int(lo*100):>2d}-{int(hi*100):<2d}%      {r['freq']*100:5.0f}% "
              f"{med:>10s} {_fmt_pct(r['p_recover'],14)}")
    print()


def print_company_tables(cres, thr):
    decomp = cres["decomposition"]
    print("=" * 74)
    print("TABLE 3 -- Company premium decomposition (the anatomy of each multiple)")
    print("=" * 74)
    print(f"{'Name':9s} {'Pen':>5s} {'fwdPE':>6s} {'Prem':>5s} {'Just':>5s} {'Float':>6s} "
          f"{'Frag':>5s} {'RecovQ':>7s} {'Dom':>4s} {'Cpx':>4s}")
    order = sorted(decomp, key=lambda n: decomp[n]["fragility"])
    for nm in order:
        o = decomp[nm]
        print(f"{nm:9s} {o['pen']*100:4.0f}% {o['fwd_pe']:6.0f} {o['premium_pts']:5.0f} "
              f"{o['justified_pts']:5.0f} {o['unsupported_pts']:6.1f} "
              f"{o['fragility']*100:4.0f}% {o['recovery_quality']*100:6.0f}% "
              f"{o['dominance']:4.2f} {o['capex_elastic']:4.2f}")
    print()

    print("=" * 74)
    print("TABLE 4 -- Same wound, different healing (18-month horizon)")
    print("           beta sets the drawdown depth; TAM sets the recovery")
    print("=" * 74)
    print(f"{'Name':9s} {'P(DD>25%)':>10s} {('P(rec<'+str(int(C.MANDATE_MONTHS))+'m|DD>25%)'):>22s} {'RecovQ':>7s}")
    for nm in order:
        rc = cres["recovery_cond"][nm]
        print(f"{nm:9s} {_fmt_pct(rc['p_dd25'],10)} {_fmt_pct(rc['p_recover'],22)} "
              f"{rc['recovery_quality']*100:6.0f}%")
    print()

    # ---- TABLE 4b: the permanent tail + recovery curve (catastrophe signal) ----
    rc0 = cres["recovery_cond"]
    if rc0 and ("p_never" in next(iter(rc0.values()))):
        print("=" * 74)
        print("TABLE 4b -- Recovery CURVE and the PERMANENT tail (cond. on DD>25%)")
        print("            P(never) = still underwater at end of sim = the core")
        print("            catastrophe signal. Ordered by P(never); lower is safer.")
        print("=" * 74)
        def _cv(rc, m):
            for pt in rc.get("recovery_curve", []) or []:
                if pt["months"] == m:
                    return pt["p_recovered"]
            return float("nan")
        print(f"{'Name':9s} {'rec18m':>7s} {'rec24m':>7s} {'rec36m':>7s} {'P(never)':>9s}")
        for nm in sorted(rc0, key=lambda n: (rc0[n]['p_never']
                                             if rc0[n]['p_never'] == rc0[n]['p_never']
                                             else 1.0)):
            rc = rc0[nm]
            print(f"{nm:9s} {_fmt_pct(_cv(rc,18),7)} {_fmt_pct(_cv(rc,24),7)} "
                  f"{_fmt_pct(_cv(rc,36),7)} {_fmt_pct(rc['p_never'],9)}")
        print()


def sensitivity_sweep(deltas=(("quality", 0.15), ("earn_quality", 0.15),
                              ("dominance", 0.15), ("capex_elastic", 0.15))):
    """Re-derive the recovery ranking with each judgment score shifted +/- delta,
    to reveal which orderings are robust and which depend on a chosen number.
    This is the honesty check: it runs only the (fast) decomposition, not the
    full Monte Carlo, because the recovery RANKING is set by recovery_quality.
    """
    print("=" * 74)
    print("TABLE 5 -- Sensitivity: recovery-rank stability under +/-score shifts")
    print("           robust tiers vs. calibration-dependent fine ordering")
    print("=" * 74)
    scenarios = {"base": []}
    for field, d in deltas:
        scenarios[f"{field}+"] = [(field, +d)]
        scenarios[f"{field}-"] = [(field, -d)]

    rankings = {}
    for label, shifts in scenarios.items():
        comp = copy.deepcopy(C.COMPANIES)
        for field, d in shifts:
            for v in comp.values():
                v[field] = float(np.clip(v[field] + d, 0, 1))
        dec = E.decompose_premium(comp)
        rankings[label] = sorted(dec, key=lambda n: -dec[n]["recovery_quality"])

    names = list(C.COMPANIES.keys())
    cols = list(scenarios.keys())
    # print as rank rows
    print(f"{'Rank':5s} " + " ".join(f"{c:13s}" for c in cols[:5]))
    for i in range(len(names)):
        print(f"{i+1:4d}  " + " ".join(f"{rankings[c][i]:13s}" for c in cols[:5]))
    print("  (showing first 5 scenario columns; full set saved to results.json)")
    print()

    # robustness summary: who never moves from top/bottom tier
    top_always = set(rankings["base"][:3])
    bot_always = set(rankings["base"][-2:])
    for label in rankings:
        top_always &= set(rankings[label][:3])
        bot_always &= set(rankings[label][-2:])
    print(f"  ROBUST top tier (recovers well in every scenario): {sorted(top_always)}")
    print(f"  ROBUST bottom tier (recovers poorly in every scenario): {sorted(bot_always)}")
    print()
    return rankings


def reconciliation_note():
    print("=" * 74)
    print("SYSTEMIC-TAIL RECONCILIATION (two independent methods)")
    print("=" * 74)
    d = C.derive_regime_probs()
    print("  Simulation tail (emergent) vs. hazard-derived tail vs. reconciled range:")
    for i, hz in enumerate(C.HORIZON_LABELS):
        sim = C.REGIME_PROBS["systemic"][i]
        haz = d["systemic"][i]
        lo, hi = C.SYSTEMIC_TAIL_RECONCILED[hz]
        print(f"    {hz:4s}  calibrated={sim*100:4.1f}%   hazard={haz*100:4.1f}%   "
              f"reconciled={lo*100:.0f}-{hi*100:.0f}%")
    print()


def main():
    print("#" * 74)
    print(f"#  SYSTEMIC + TAM RISK MODEL   |   calibrated as of {C.AS_OF_DATE}")
    print(f"#  {C.SIM['n_paths']:,} paths  |  horizons {C.HORIZON_LABELS}  |  mandate {int(C.MANDATE_MONTHS)}m (suggested edge)")
    _ss = C.SYSTEMIC_STRESS
    print(f"#  macro-stress index {_ss['score']*100:.0f}/100 "
          f"(structural {_ss['structural']*100:.0f} / acute {_ss['acute']*100:.0f}) "
          f"-> crisis x{C.STRESS_CRISIS_MULT:.2f}")
    print(f"#  THIS IS A RESEARCH MODEL, NOT INVESTMENT ADVICE.")
    print("#" * 74)

    print("\n[1/3] Running broad-exposure Monte Carlo ...")
    eres, thr = E.run_exposures(verbose=True)
    print_exposure_tables(eres, thr)
    print_recovery_table(eres)

    print("[2/3] Running TAM-adjusted company Monte Carlo ...")
    cres, cthr = E.run_companies(verbose=True)
    print_company_tables(cres, cthr)

    print("[3/3] Sensitivity sweep + reconciliation ...")
    rankings = sensitivity_sweep()
    reconciliation_note()

    # ---- save everything to one results file (numpy -> python types) ----
    def clean(o):
        if isinstance(o, dict):  return {k: clean(v) for k, v in o.items()}
        if isinstance(o, (list, tuple)): return [clean(x) for x in o]
        if isinstance(o, (np.floating,)): return float(o)
        if isinstance(o, (np.integer,)):  return int(o)
        return o
    results = {
        "as_of": C.AS_OF_DATE,
        "macro": C.MACRO,
        "regime_probs": C.REGIME_PROBS,
        "exposures": clean(eres),
        "companies": clean(cres),
        "sensitivity": rankings,
        "thresholds": list(thr),
    }
    with open("results.json", "w") as f:
        json.dump(_clean_json(results), f, indent=1, allow_nan=False)
    print("Saved results.json  (feed this to the report generator).")
    print("\nDONE.  To update: edit calibration.py, re-run this file.")


if __name__ == "__main__":
    main()
